export const pricingData = [
    {
      id: 1,
      title: "BRONCE",
      img: "/images/pricing/noto_star-1.png",
      description: "You can create up to 3 Bronze chains to invite up to 39 friends in each to win together",
      buys: "$100.00",
      revenue: "$211.50",
      color: "text-[#CD7F32]",
      bgColor: "bg-[#F0EBE6]",
    },
    {
      id: 2,
      title: "SILVER",
      img: "/images/pricing/noto_star-2.png",
      description: "You can create up to 3 Silver chains to invite up to 39 friends in each to win together",
      buys: "$200.00",
      revenue: "$540.00",
      color: "text-[#A6A6A6]",
      bgColor: "bg-[#F7F7F7]",
    },
    {
      id: 3,
      title: "GOLD",
      img: "/images/pricing/noto_star-3.png",
      description: "You can create up to 3 Gold chains to invite up to 39 friends in each to win together",
      buys: "$300.00",
      revenue: "$985.50",
      color: "text-[#E5C100]",
      bgColor: "bg-[#FFFBE5]",
    },
    {
      id: 4,
      title: "PLATINO",
      img: "/images/pricing/noto_star-4.png",
      description: "You can create up to 3 Platino chains to invite up to 39 friends in each to win together",
      buys: "$100.00",
      revenue: "$211.50",
      color: "text-[#85A68D]",
      bgColor: "bg-[#E6F2E9]",
    },
    {
      id: 5,
      title: "Diamante",
      img: "/images/pricing/noto_star-5.png",
      description: "You can create up to 3 Diamante chains to invite up to 39 friends in each to win together",
      buys: "$100.00",
      revenue: "$211.50",
      color: "text-[#8AC6D1]",
      bgColor: "bg-[#E6F0F2]",
    },
  ];